apiVersion: v1
kind: Service
metadata: 
  name: student-app-client-service
spec:
  selector: {{ include "common.client" . | nindent 4 }}
  ports:
    - port: {{ .Values.client.port }}
      protocol: TCP
      targetPort: {{ .Values.client.targetPort }}
  type: ClusterIP
